-- MySQL Script generated by MySQL Workbench
-- Sat Mar 26 11:19:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema soft-receipts
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema soft-receipts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `soft-receipts` DEFAULT CHARACTER SET utf8 ;
USE `soft-receipts` ;

-- -----------------------------------------------------
-- Table `soft-receipts`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft-receipts`.`Login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `timestamps` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `state` TINYINT(4) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idLogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soft-receipts`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft-receipts`.`Productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(100) NOT NULL,
  `titular` VARCHAR(100) NOT NULL,
  `peso` VARCHAR(100) NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `precio` VARCHAR(100) NOT NULL,
  `precio_unidad` VARCHAR(100) NOT NULL,
  `creado_por` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `timestamps` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `state` TINYINT(4) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idProductos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
